#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 15 05:46:47 2019

@author: rebeccawang
"""

import pandas as pd

def convert_age_cell(cell):
    if cell == 16:
        return 88
    return cell
df = pd.read_excel("pd_exm1.xlsx", "Sheet1", converters = {
        'age': convert_age_cell
        })

print(df)

df.to_excel("new_exm1.xlsx", sheet_name = "stocks")